### ISSUE TITLE
The log facility is not working as expected. All messages will be written to the standard error stream.

### ISSUE THREAD

**Issue by altjx** [greenbone/openvas-scanner#784] opened 2021-06-23 22:13 UTC
I am installing openvas in a Docker image that I am building and deploying, but the docker build keeps failing. I am pretty certain it is due to the following output from `gvm-setup`:

![Screen Shot 2021-06-23 at 6 14 03 PM](https://user-images.githubusercontent.com/4023423/123174842-cb671480-d44e-11eb-897a-d8843ca8df01.png)

This is the last thing that the dockerfile shows before exiting and failing. The only command that I am running for this is `gvm-setup > ~/.openvas_install_logs.txt`.

How do I work around this? I have no clue what the "log facility" is. Every tutorial that I see referring to installing OpenVAS inside of a VM such as Kali just simply say run `gvm-setup`, so the setup process is completely unattended and straight forward.

**Comment by ArnoStiefvater** [comment] 2021-07-19 04:50
Please note that gvm-setup is a 3rdparty script not provided / maintained by Greenbone.
We now have [official installation guides](https://greenbone.github.io/docs/) which can be used for installing GVM.

I'm closing this issue as invalid for now as this is most likely not a bug but a problem with the install script.

If this issue persists even after using the official install guide please use the community forum at https://community.greenbone.net/c/gse instead of Github. Github is for bugs, community portal for support questions.

**Closed by ArnoStiefvater** 2021-07-19 04:50 UTC
