### ISSUE TITLE
openvas scanner build horking on gvm-lib mismatch

### ISSUE THREAD

**Issue by PhlegmingChee** [greenbone/openvas-scanner#674] opened 2021-03-04 19:15 UTC
I've pulled the latest 20.08 sources and when I run the make in the openvas tree it fails on the module check:
`-- Checking for module 'libgvm_base>=21.4'`
`-- Requested 'libgvm_base >= 21.4' but version of gvmlibs-base is 20.8.2-git-22a7702-gvm-libs-20.08`

The gvm-libs built with no issue. This is on Ubuntu 20.04

**Comment by cfi-gb** [comment] 2021-03-05 07:04
Seems the `master` / development branch containing the "openvas-scanner" version 21.04 got accidentally merged into the stable branch of 20.08 with https://github.com/greenbone/openvas-scanner/commit/bb1040330953da12a086e68a5ff7cbe8dc9a600a

cc @jjnicola

**Comment by jjnicola** [comment] 2021-03-05 08:02
Hi @PhlegmingChee ,
Thanks for reporting this. The issue is already fixed.

**Closed by jjnicola** 2021-03-05 08:02 UTC
Labels: bug

**Comment by PhlegmingChee** [comment] 2021-03-05 12:31
Yep. Working now. Thanks.
