### ISSUE TITLE
[Rust] Circular error unable to find scan because unable to find scan

### ISSUE THREAD

**Issue by mryellow** [greenbone/openvas-scanner#1747] opened 2024-10-29 00:50 UTC
### Expected behavior

Return an error on errors.

### Actual behavior

```
2024-10-29T00:49:08.027125Z  WARN openvasd::scheduling: unable to fetch results scan_id=dea07b91-461f-46d7-aa14-f29b7be9185d e=Unexpected issue: InvalidResponse(Status { text: "Failed to find scan 'dea07b91-461f-46d7-aa14-f29b7be9185d'", code: StringU32(404) })
```

### Steps to reproduce

Will attempt to find the exact `oid` which causes the invalid "404".

By including `oid` one-by-one until it fails, as logs do not indicate what is currently being processed.

**Comment by nichtsfrei** [comment] 2024-10-29 08:41
Is that a duplicate of https://github.com/greenbone/openvas-scanner/issues/1744?

**Comment by mryellow** [comment] 2024-10-29 12:36
Looking closer, it could be.

It seems to indicate some sub-component returned an error with a `404`, which then the wrapper reported as a warning with a `text` from that inner error.

The "repeating over and over" seems to be some kind of internal retry. Which keeps on reporting a `404`, where the majority of #1744 isn't that loop, but the initial XML parsing failure and subsequent loss of the socket.

**Comment by nichtsfrei** [comment] 2024-11-04 08:14
That looping behavior will be fixed as well when the scan status is changed to fail, as it removes the scan from the checked background task.

**Closed** 2024-11-07 12:43 UTC
Labels: bug, duplicate
