### ISSUE TITLE
Please provide a simple TL;DR one liner to start the GVM Docker image (https://hub.docker.com/r/greenbone/openvas-scanner)

### ISSUE THREAD

**Issue by huornlmj** [greenbone/openvas-scanner#1501] opened 2023-09-19 10:48 UTC
Could anyone please provide a simple one liner on how to start the GVM docker images from https://hub.docker.com/r/greenbone/openvas-scanner.

**Comment by jjnicola** [comment] 2023-09-19 11:08
Hi @huornlmj ,

This is not a bug issue but a support question. Therefore, closing the issue as invalid.
Please, visit the [Greenbone Forum](https://forum.greenbone.net/).

**Closed by jjnicola** 2023-09-19 11:08 UTC
Labels: invalid

**Comment by huornlmj** [comment] 2023-09-19 11:52
@jjnicola perhaps you could update the link to the Forum in the issues link as it currently points to the wrong page.
