### ISSUE TITLE
"Create Target Failed" when target list is > 4096

### ISSUE THREAD

**Issue by binkleym** [greenbone/openvas-scanner#96] opened 2018-05-10 19:24 UTC
### Expected behavior

Trying to run OpenVAS on our academic compute cluster internal network which is spread across a /16.  I should be able to enter "10.0.0.0/16" as a host target.

### Current behavior

When I enter anything much larger than a /24, it barfs with "Create Target Failed"

### Steps to reproduce
1.  Open GSA.  Click on "Configuration -> Targets"
2.  Click on "*" to create new target.
3.  Enter "10.0.0.0/16", or a file with an equivalent list of hosts.

### GVM versions
**gsa:** (gsad --version)

Greenbone Security Assistant 7.0.3

**gvm:** (gvmd --version)

None

**openvas-scanner:** (openvassd --version)

OpenVAS Scanner 5.1.2

**gvm-libs:**

None

**openvas-smb:**

None

### Environment
**Operating system:**

Ubuntu Xenial 16.04 AMD64

**Installation method / source:** (packages, source installation)

PPA at https://launchpad.net/~mrazavi/+archive/ubuntu/openvas

Install was verified as working with "openvas-check-setup --v9"

### Logfiles

```

```

**Comment by 128432b4117** [comment] 2018-05-11 04:58
@binkleym For the CIDR notation this is the expected behavior. You can find the following text if you click on the small help button on the top left of the targets page within the GSA:

> The netmask in CIDR notation is limited to 20 for IPv4 and 116 for IPv6 (4095 hosts). 

Additionally the openvas-scanner isn't managing the target list on its own so the repository here currently doesn't fit. I would suggest to close here and follow-up with a post to http://lists.wald.intevation.org/pipermail/openvas-discuss/ on how to handle such large target lists.

**Comment by cfi-gb** [comment] 2018-05-11 05:02
@binkleym This is the current and expected behavior for the CIDR notation. If you open the help page of the targets list (the little question mark at the top left) within the GSA you can find this text:

> The netmask in CIDR notation is limited to 20 for IPv4 and 116 for IPv6 (4095 hosts). 

I suggest to close here and follow up with a mailing list post to http://lists.wald.intevation.org/cgi-bin/mailman/listinfo/openvas-discuss on how to handle such larger target lists.

**Comment by jjnicola** [comment] 2018-05-14 10:33
For the reasons explained by @cfi-gb, close the issue here.

**Closed by jjnicola** 2018-05-14 10:33 UTC
